name: Open PR to `gh-pages`
on:
  push:
    branches:
      - master
jobs:
  pr-to-gh-pages:
    name: open-pr-to-gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: pull-request-action
        uses: vsoch/pull-request-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_PREFIX: "master"
          PULL_REQUEST_BRANCH: "gh-pages"
          PULL_REQUEST_TITLE: "Update presentation"
